@IsTest
public with sharing class TestDataFactory_PlatformAdmin {
    public static String int_environment_query_response =
        '{' +
        '  "status": 0,' +
        '  "result": {' +
        '    "size": 2,' +
        '    "totalSize": 2,' +
        '    "done": true,' +
        '    "queryLocator": null,' +
        '    "entityTypeName": "InstalledSubscriberPackage",' +
        '    "records": [' +
        '      {' +
        '        "attributes": {' +
        '          "type": "InstalledSubscriberPackage",' +
        '          "url": "/services/data/v48.0/tooling/sobjects/InstalledSubscriberPackage/0A32o000000VIX7CAO"' +
        '        },' +
        '        "Id": "0A32o000000VIX7CAO",' +
        '        "SubscriberPackageId": "0332o000000TyICAA0",' +
        '        "SubscriberPackage": {' +
        '          "attributes": {' +
        '            "type": "SubscriberPackage",' +
        '            "url": "/services/data/v48.0/tooling/sobjects/SubscriberPackage/0332o000000TyICAA0"' +
        '          },' +
        '          "Name": "fflib-apex-mocks"' +
        '        },' +
        '        "SubscriberPackageVersion": {' +
        '          "attributes": {' +
        '            "type": "SubscriberPackageVersion",' +
        '            "url": "/services/data/v48.0/tooling/sobjects/SubscriberPackageVersion/04t2o000001MwxDAAS"' +
        '          },' +
        '          "Id": "04t2o000001MwxDAAS",' +
        '          "Description": null,' +
        '          "IsBeta": false,' +
        '          "IsPasswordProtected": true,' +
        '          "MajorVersion": 0,' +
        '          "MinorVersion": 6,' +
        '          "PatchVersion": 0,' +
        '          "BuildNumber": 1' +
        '        }' +
        '      },' +
        '      {' +
        '        "attributes": {' +
        '          "type": "InstalledSubscriberPackage",' +
        '          "url": "/services/data/v48.0/tooling/sobjects/InstalledSubscriberPackage/0A32o000000VHvwCAG"' +
        '        },' +
        '        "Id": "0A32o000000VHvwCAG",' +
        '        "SubscriberPackageId": "0332o000000TyIHAA0",' +
        '        "SubscriberPackage": {' +
        '          "attributes": {' +
        '            "type": "SubscriberPackage",' +
        '            "url": "/services/data/v48.0/tooling/sobjects/SubscriberPackage/0332o000000TyIHAA0"' +
        '          },' +
        '          "Name": "fflib-apex-common"' +
        '        },' +
        '        "SubscriberPackageVersion": {' +
        '          "attributes": {' +
        '            "type": "SubscriberPackageVersion",' +
        '            "url": "/services/data/v48.0/tooling/sobjects/SubscriberPackageVersion/04t2o000001MwxIAAS"' +
        '          },' +
        '          "Id": "04t2o000001MwxIAAS",' +
        '          "Description": null,' +
        '          "IsBeta": false,' +
        '          "IsPasswordProtected": true,' +
        '          "MajorVersion": 0,' +
        '          "MinorVersion": 3,' +
        '          "PatchVersion": 0,' +
        '          "BuildNumber": 1' +
        '        }' +
        '      }' +
        '    ]' +
        '  }' +
        '}';

    public static String uat_environment_query_response =
        '{' +
        '  "status": 0,' +
        '  "result": {' +
        '    "size": 2,' +
        '    "totalSize": 2,' +
        '    "done": true,' +
        '    "queryLocator": null,' +
        '    "entityTypeName": "InstalledSubscriberPackage",' +
        '    "records": [' +
        '      {' +
        '        "attributes": {' +
        '          "type": "InstalledSubscriberPackage",' +
        '          "url": "/services/data/v48.0/tooling/sobjects/InstalledSubscriberPackage/0A32o000000VIX7CAO"' +
        '        },' +
        '        "Id": "0A32o000000VIX7CAO",' +
        '        "SubscriberPackageId": "0332o000000TyICAA0",' +
        '        "SubscriberPackage": {' +
        '          "attributes": {' +
        '            "type": "SubscriberPackage",' +
        '            "url": "/services/data/v48.0/tooling/sobjects/SubscriberPackage/0332o000000TyICAA0"' +
        '          },' +
        '          "Name": "fflib-apex-mocks"' +
        '        },' +
        '        "SubscriberPackageVersion": {' +
        '          "attributes": {' +
        '            "type": "SubscriberPackageVersion",' +
        '            "url": "/services/data/v48.0/tooling/sobjects/SubscriberPackageVersion/04t2o000001MwxDAAS"' +
        '          },' +
        '          "Id": "04t2o000001MwxDAAS",' +
        '          "Description": null,' +
        '          "IsBeta": false,' +
        '          "IsPasswordProtected": true,' +
        '          "MajorVersion": 0,' +
        '          "MinorVersion": 6,' +
        '          "PatchVersion": 0,' +
        '          "BuildNumber": 1' +
        '        }' +
        '      }' +
        '    ]' +
        '  }' +
        '}';
}
